import { spawn } from 'node:child_process';
import { open } from 'node:fs/promises';

export const PROVIDER_BUDGET_SCHEMA = 'arcp.provider-budget/v1' as const;
const MAX_TEXT = 160;
const MAX_ERROR = 240;
const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;
const SECRET = /(?:bearer\s+\S+|authorization\s*[:=]|cookie\s*[:=]|(?:api[_-]?key|token|secret|password)\s*[:=]|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|eyJ[A-Za-z0-9_-]{20,}|[A-Za-z0-9_-]{40,})/i;

export type ProviderBudgetEnvelopeV1 = { schemaVersion: typeof PROVIDER_BUDGET_SCHEMA; source: { id: string; kind: 'paseo' | 'command'; observedAt: string; freshnessMs?: number }; providers: ProviderBudgetProvider[] };
export type ProviderBudgetProvider = { providerId: string; displayName?: string; status: 'available' | 'unavailable' | 'error'; planLabel?: string | null; sourceLabel?: string | null; fetchedAt?: string | null; nextRefreshAt?: string | null; windows: ProviderBudgetWindow[]; balances?: ProviderBudgetBalance[]; modelBindings?: Array<{ modelPattern: string; windowIds: string[] }>; error?: string | null };
export type ProviderBudgetWindow = { id: string; label: string; usedPct?: number | null; remainingPct?: number | null; resetsAt?: string | null; runsOutAt?: string | null; shortfallPct?: number | null; scope?: 'session' | 'weekly' | 'other' };
export type ProviderBudgetBalance = { id: string; label: string; used?: number | null; remaining?: number | null; limit?: number | null; unit: 'usd' | 'credits' | 'requests' | 'tokens'; resetsAt?: string | null };
export type ProviderBudgetBinding = { id?: string; providerId: string; sourceId: string; modelPatterns?: string[]; windowIds: string[]; admissionPolicyId: string };
export type ProviderBudgetPolicy = { id: string; maxAgeMs: number; drainRemainingPct: number; hardDrainRemainingPct: number; requiredPaidUnattended?: boolean; recommendedProviderProfile?: string };
export type AdmissionDecision = { action: 'launch' | 'route' | 'drain' | 'hard_drain' | 'hold_stale' | 'hold_unknown'; providerId: string; model: string; bindingId?: string; snapshotObservedAt?: string; reasons: string[]; relevantWindows: string[]; recommendedProviderProfile?: string };
export type ProviderBudgetConfig = { sources?: Array<{ id: string; kind: 'paseo' | 'command' | 'codexbar' | 'pi-grok-cache'; command?: string[]; cachePath?: string; timeoutMs?: number; maxOutputBytes?: number; maxAgeMs?: number; envAllowlist?: string[] }>; bindings?: ProviderBudgetBinding[]; policies?: ProviderBudgetPolicy[] };

function record(value: unknown, name: string): Record<string, any> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${name} must be an object`); return value as Record<string, any>; }
function keys(value: Record<string, any>, allowed: string[], name: string) { for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new Error(`${name}.${key} is not allowed`); }
function text(value: unknown, name: string, nullable = false): string | null | undefined { if (value === undefined) return undefined; if (value === null && nullable) return null; if (typeof value !== 'string' || !value.trim() || value.length > MAX_TEXT || SECRET.test(value)) throw new Error(`${name} is invalid`); return value; }
function date(value: unknown, name: string, nullable = false): string | null | undefined { const result = text(value, name, nullable); if (result === undefined || result === null) return result; if (!ISO.test(result) || !Number.isFinite(Date.parse(result))) throw new Error(`${name} must be an ISO date-time`); return result; }
function pct(value: unknown, name: string): number | null | undefined { if (value === undefined) return undefined; if (value === null) return null; if (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > 100) throw new Error(`${name} must be a percentage`); return value; }
function number(value: unknown, name: string): number | null | undefined { if (value === undefined) return undefined; if (value === null) return null; if (typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`${name} must be finite`); return value; }

export function validateProviderBudgetEnvelope(input: unknown): ProviderBudgetEnvelopeV1 {
  const root = record(input, 'envelope'); keys(root, ['schemaVersion', 'source', 'providers'], 'envelope'); if (root.schemaVersion !== PROVIDER_BUDGET_SCHEMA) throw new Error('unsupported provider budget schema');
  const source = record(root.source, 'source'); keys(source, ['id', 'kind', 'observedAt', 'freshnessMs'], 'source'); const id = text(source.id, 'source.id')!; if (source.kind !== 'paseo' && source.kind !== 'command') throw new Error('source.kind is invalid'); const observedAt = date(source.observedAt, 'source.observedAt')!; if (source.freshnessMs !== undefined && (!Number.isInteger(source.freshnessMs) || source.freshnessMs < 0)) throw new Error('source.freshnessMs is invalid');
  if (!Array.isArray(root.providers) || root.providers.length > 32) throw new Error('providers must be a bounded array'); const providerIds = new Set<string>();
  const providers = root.providers.map((raw, providerIndex) => {
    const provider = record(raw, `providers[${providerIndex}]`); keys(provider, ['providerId','displayName','status','planLabel','sourceLabel','fetchedAt','nextRefreshAt','windows','balances','modelBindings','error'], `providers[${providerIndex}]`);
    const providerId = text(provider.providerId, 'providerId')!; if (providerIds.has(providerId)) throw new Error('duplicate providerId'); providerIds.add(providerId); if (!['available','unavailable','error'].includes(provider.status)) throw new Error('provider status is invalid');
    if (!Array.isArray(provider.windows) || provider.windows.length > 32) throw new Error('windows must be a bounded array'); const windowIds = new Set<string>();
    const windows = provider.windows.map((rawWindow: unknown, index: number) => { const w = record(rawWindow, `windows[${index}]`); keys(w, ['id','label','usedPct','remainingPct','resetsAt','runsOutAt','shortfallPct','scope'], 'window'); const windowId = text(w.id, 'window.id')!; if (windowIds.has(windowId)) throw new Error('duplicate window id'); windowIds.add(windowId); let used = pct(w.usedPct, 'window.usedPct'); let remaining = pct(w.remainingPct, 'window.remainingPct'); if (used === undefined && remaining === undefined) throw new Error('window needs usedPct or remainingPct'); if (used === undefined) used = remaining === null ? null : 100 - remaining!; if (remaining === undefined) remaining = used === null ? null : 100 - used!; if (used !== null && remaining !== null && Math.abs((used + remaining) - 100) > 0.1) throw new Error('window percentages disagree'); if (w.scope !== undefined && !['session','weekly','other'].includes(w.scope)) throw new Error('window.scope is invalid'); return { id: windowId, label: text(w.label, 'window.label')!, usedPct: used, remainingPct: remaining, ...(date(w.resetsAt, 'window.resetsAt', true) !== undefined ? { resetsAt: date(w.resetsAt, 'window.resetsAt', true) } : {}), ...(date(w.runsOutAt, 'window.runsOutAt', true) !== undefined ? { runsOutAt: date(w.runsOutAt, 'window.runsOutAt', true) } : {}), ...(pct(w.shortfallPct, 'window.shortfallPct') !== undefined ? { shortfallPct: pct(w.shortfallPct, 'window.shortfallPct') } : {}), ...(w.scope !== undefined ? { scope: w.scope as ProviderBudgetWindow['scope'] } : {}) }; });
    const balanceIds = new Set<string>(); const balances = provider.balances === undefined ? undefined : (() => { if (!Array.isArray(provider.balances) || provider.balances.length > 32) throw new Error('balances must be bounded'); return provider.balances.map((rawBalance: unknown) => { const b = record(rawBalance, 'balance'); keys(b, ['id','label','used','remaining','limit','unit','resetsAt'], 'balance'); const balanceId = text(b.id, 'balance.id')!; if (balanceIds.has(balanceId)) throw new Error('duplicate balance id'); balanceIds.add(balanceId); if (!['usd','credits','requests','tokens'].includes(b.unit)) throw new Error('balance.unit is invalid'); return { id: balanceId, label: text(b.label, 'balance.label')!, ...(number(b.used, 'balance.used') !== undefined ? { used: number(b.used, 'balance.used') } : {}), ...(number(b.remaining, 'balance.remaining') !== undefined ? { remaining: number(b.remaining, 'balance.remaining') } : {}), ...(number(b.limit, 'balance.limit') !== undefined ? { limit: number(b.limit, 'balance.limit') } : {}), unit: b.unit as ProviderBudgetBalance['unit'], ...(date(b.resetsAt, 'balance.resetsAt', true) !== undefined ? { resetsAt: date(b.resetsAt, 'balance.resetsAt', true) } : {}) }; }); })();
    const modelBindings = provider.modelBindings === undefined ? undefined : (() => { if (!Array.isArray(provider.modelBindings) || provider.modelBindings.length > 32) throw new Error('modelBindings must be bounded'); return provider.modelBindings.map((rawBinding: unknown) => { const binding = record(rawBinding, 'modelBinding'); keys(binding, ['modelPattern','windowIds'], 'modelBinding'); const modelPattern = text(binding.modelPattern, 'modelPattern')!; if (!/^[A-Za-z0-9._/*:-]+$/.test(modelPattern) || (modelPattern.match(/\*/g) ?? []).length > 1) throw new Error('modelPattern is invalid'); if (!Array.isArray(binding.windowIds) || !binding.windowIds.length || binding.windowIds.some((id: unknown) => typeof id !== 'string' || !windowIds.has(id))) throw new Error('model binding references unknown window'); return { modelPattern, windowIds: [...binding.windowIds] }; }); })();
    return { providerId, ...(text(provider.displayName, 'displayName') !== undefined ? { displayName: text(provider.displayName, 'displayName')! } : {}), status: provider.status as ProviderBudgetProvider['status'], ...(text(provider.planLabel, 'planLabel', true) !== undefined ? { planLabel: text(provider.planLabel, 'planLabel', true) } : {}), ...(text(provider.sourceLabel, 'sourceLabel', true) !== undefined ? { sourceLabel: text(provider.sourceLabel, 'sourceLabel', true) } : {}), ...(date(provider.fetchedAt, 'fetchedAt', true) !== undefined ? { fetchedAt: date(provider.fetchedAt, 'fetchedAt', true) } : {}), ...(date(provider.nextRefreshAt, 'nextRefreshAt', true) !== undefined ? { nextRefreshAt: date(provider.nextRefreshAt, 'nextRefreshAt', true) } : {}), windows, ...(balances ? { balances } : {}), ...(modelBindings ? { modelBindings } : {}), ...(text(provider.error, 'error', true) !== undefined ? { error: text(provider.error, 'error', true) } : {}) };
  });
  return { schemaVersion: PROVIDER_BUDGET_SCHEMA, source: { id, kind: source.kind, observedAt, ...(source.freshnessMs !== undefined ? { freshnessMs: source.freshnessMs } : {}) }, providers };
}

export function redactProviderText(value: unknown): string { return SECRET.test(String(value ?? '')) ? '<redacted>' : String(value ?? '').replace(/[\r\n]+/g, ' ').slice(0, MAX_ERROR); }
export function matchesModel(pattern: string, model: string): boolean { const escaped = pattern.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace('*', '.*'); return new RegExp(`^${escaped}$`).test(model); }
export function evaluateAdmission(input: { envelope?: ProviderBudgetEnvelopeV1; bindings: ProviderBudgetBinding[]; policies: ProviderBudgetPolicy[]; providerId: string; model: string; unattended?: boolean; activeRuntimeCount?: number; now?: number }): AdmissionDecision {
  const candidate = input.bindings.find((item) => item.providerId === input.providerId && (!item.modelPatterns?.length || item.modelPatterns.some((pattern) => matchesModel(pattern, input.model)))); const binding = input.bindings.find((item) => item.providerId === input.providerId && item.sourceId === input.envelope?.source.id && (!item.modelPatterns?.length || item.modelPatterns.some((pattern) => matchesModel(pattern, input.model)))); const base = { providerId: input.providerId, model: input.model, ...(binding?.id ? { bindingId: binding.id } : {}), reasons: [] as string[], relevantWindows: [] as string[] };
  if (!binding) { const required = Boolean(input.unattended || (candidate && input.policies.find((policy) => policy.id === candidate.admissionPolicyId)?.requiredPaidUnattended)); return { ...base, action: required ? 'hold_unknown' : 'launch', reasons: required ? ['configured provider budget snapshot is unavailable'] : ['no provider budget binding'] }; }
  const policy = input.policies.find((item) => item.id === binding.admissionPolicyId); if (!policy || !input.envelope || input.envelope.source.id !== binding.sourceId) return { ...base, action: 'hold_unknown', reasons: ['provider budget snapshot is unavailable'] };
  if (Date.parse(input.envelope.source.observedAt) + policy.maxAgeMs < (input.now ?? Date.now())) return { ...base, action: 'hold_stale', snapshotObservedAt: input.envelope.source.observedAt, reasons: ['provider budget snapshot is stale'] };
  const provider = input.envelope.providers.find((item) => item.providerId === input.providerId); if (!provider || provider.status !== 'available') return { ...base, action: 'hold_unknown', snapshotObservedAt: input.envelope.source.observedAt, reasons: ['provider budget is unavailable'] };
  const windows = provider.windows.filter((item) => binding.windowIds.includes(item.id)); if (windows.length !== binding.windowIds.length || windows.some((item) => item.remainingPct === null)) return { ...base, action: 'hold_unknown', snapshotObservedAt: input.envelope.source.observedAt, reasons: ['bound provider budget window is unknown or missing'] };
  const drain = windows.filter((item) => (item.remainingPct ?? 101) <= policy.drainRemainingPct || Boolean(item.runsOutAt && item.resetsAt && Date.parse(item.runsOutAt) < Date.parse(item.resetsAt)));
  const hard = windows.filter((item) => (item.remainingPct ?? 101) <= policy.hardDrainRemainingPct);
  const recommendation = policy.recommendedProviderProfile ? { recommendedProviderProfile: policy.recommendedProviderProfile } : {};
  if (hard.length) return { ...base, ...recommendation, action: 'hard_drain', snapshotObservedAt: input.envelope.source.observedAt, reasons: ['provider budget is in HARD_DRAIN'], relevantWindows: hard.map((item) => item.id) };
  if (drain.length) return { ...base, ...recommendation, action: 'drain', snapshotObservedAt: input.envelope.source.observedAt, reasons: ['provider budget is in DRAIN'], relevantWindows: drain.map((item) => item.id) };
  return { ...base, action: 'launch', snapshotObservedAt: input.envelope.source.observedAt, reasons: ['provider budget permits launch'], relevantWindows: windows.map((item) => item.id) };
}

export async function runCommandCollector(source: NonNullable<ProviderBudgetConfig['sources']>[number]): Promise<ProviderBudgetEnvelopeV1> {
  if (source.kind !== 'command' || !source.command?.length || !source.command[0].startsWith('/')) throw new Error('command collector requires an absolute argv executable'); const output = await run(source.command[0], source.command.slice(1), source.timeoutMs ?? 30_000, source.maxOutputBytes ?? 262144, source.envAllowlist ?? []); if (output.code !== 0) throw new Error(`collector exited ${output.code}`); let parsed: unknown; try { parsed = JSON.parse(output.stdout); } catch { throw new Error('collector output is not one JSON envelope'); } return validateProviderBudgetEnvelope(parsed);
}
export async function collectCodexbar(sourceId = 'local-codexbar'): Promise<ProviderBudgetEnvelopeV1> {
  const bin = process.env.ARCP_CODEXBAR_BIN || '/opt/homebrew/bin/codexbar';
  const [claude, codex] = await Promise.all(['claude', 'codex'].map(async (providerId) => {
    try {
      const output = await run(bin, ['usage', '--provider', providerId, '--source', 'auto', '--format', 'json'], 30_000, 262144, ['HOME']);
      if (output.code !== 0) throw new Error('provider collector failed');
      return codexbarProvider(providerId, JSON.parse(output.stdout));
    } catch { return { providerId, status: 'error' as const, windows: [], error: 'provider collector failed' }; }
  }));
  return validateProviderBudgetEnvelope({ schemaVersion: PROVIDER_BUDGET_SCHEMA, source: { id: sourceId, kind: 'command', observedAt: new Date().toISOString(), freshnessMs: 0 }, providers: [claude, codex] });
}
/** Read a cache written by an operator-controlled Paseo Pi `/grok-cli-usage` turn.
 * It deliberately does not invoke Pi or retain the account-map key. */
export async function collectPiGrokCache(source: NonNullable<ProviderBudgetConfig['sources']>[number]): Promise<ProviderBudgetEnvelopeV1> {
  if (source.kind !== 'pi-grok-cache') throw new Error('Pi/Grok cache source is invalid');
  const configuredPath = source.cachePath === '${ARCP_PI_GROK_CACHE}' ? process.env.ARCP_PI_GROK_CACHE : source.cachePath;
  if (!configuredPath?.startsWith('/')) throw new Error('Pi/Grok cache path must be absolute'); const limit = source.maxOutputBytes ?? 16_384; if (!Number.isInteger(limit) || limit <= 0 || limit > 1_048_576) throw new Error('Pi/Grok cache byte limit is invalid'); const file = await open(configuredPath, 'r'); let bytes: Buffer; try { const buffer = Buffer.alloc(limit + 1); const { bytesRead } = await file.read(buffer, 0, buffer.length, 0); if (bytesRead > limit) throw new Error('Pi/Grok cache is unavailable'); bytes = buffer.subarray(0, bytesRead); } finally { await file.close(); }
  const root = record(JSON.parse(bytes.toString('utf8')), 'Pi/Grok cache'); keys(root, ['version','accounts'], 'Pi/Grok cache'); if (root.version !== 1) throw new Error('Pi/Grok cache version is unsupported'); const accounts = record(root.accounts, 'Pi/Grok accounts'); const entries = Object.values(accounts); if (entries.length !== 1) throw new Error('Pi/Grok cache account selection is ambiguous'); const account = record(entries[0], 'Pi/Grok account'); keys(account, ['updatedAt','tier','monthly','weekly'], 'Pi/Grok account'); const observedAt = date(account.updatedAt, 'Pi/Grok updatedAt'); if (!observedAt || Date.parse(observedAt) > Date.now() + 60_000 || Date.parse(observedAt) + (source.maxAgeMs ?? 900_000) < Date.now()) throw new Error('Pi/Grok cache is stale'); const weekly = record(account.weekly, 'Pi/Grok weekly'); keys(weekly, ['creditUsagePercent','billingPeriodEnd'], 'Pi/Grok weekly'); const monthly = account.monthly === undefined ? undefined : record(account.monthly, 'Pi/Grok monthly'); if (monthly) keys(monthly, ['monthlyLimit','used','billingPeriodEnd'], 'Pi/Grok monthly');
  const windows: ProviderBudgetWindow[] = [{ id: 'weekly', label: 'weekly', usedPct: pct(weekly.creditUsagePercent, 'Pi/Grok weekly usage')!, resetsAt: date(weekly.billingPeriodEnd, 'Pi/Grok weekly reset')!, scope: 'weekly' }]; if (monthly?.monthlyLimit && monthly.monthlyLimit > 0) windows.push({ id: 'monthly', label: 'monthly', usedPct: Math.max(0, Math.min(100, (number(monthly.used, 'Pi/Grok monthly used')! / monthly.monthlyLimit) * 100)), resetsAt: date(monthly.billingPeriodEnd, 'Pi/Grok monthly reset')!, scope: 'other' });
  return validateProviderBudgetEnvelope({ schemaVersion: PROVIDER_BUDGET_SCHEMA, source: { id: source.id, kind: 'paseo', observedAt, freshnessMs: source.maxAgeMs ?? 900_000 }, providers: [{ providerId: 'pi', status: 'available', ...(text(account.tier, 'Pi/Grok tier', true) ? { planLabel: text(account.tier, 'Pi/Grok tier', true) } : {}), sourceLabel: 'pi-grok-cli quota cache', fetchedAt: observedAt, windows }] });
}
/** Translate the documented provider.usage.list response without retaining its details payload. */
export function translatePaseoProviderUsage(sourceId: string, raw: unknown): ProviderBudgetEnvelopeV1 {
  const response = record(raw, 'Paseo provider usage'); const fetchedAt = date(response.fetchedAt, 'Paseo fetchedAt') ?? new Date().toISOString(); if (!Array.isArray(response.providers)) throw new Error('Paseo provider usage has no providers');
  return validateProviderBudgetEnvelope({ schemaVersion: PROVIDER_BUDGET_SCHEMA, source: { id: sourceId, kind: 'paseo', observedAt: fetchedAt }, providers: response.providers.map((rawProvider: unknown) => { const provider = record(rawProvider, 'Paseo provider'); const providerId = text(provider.providerId ?? provider.id, 'Paseo provider id')!; const windows = (Array.isArray(provider.windows) ? provider.windows : []).map((rawWindow: unknown) => { const window = record(rawWindow, 'Paseo window'); return { id: text(window.id, 'Paseo window id')!, label: text(window.label ?? window.id, 'Paseo window label')!, ...(window.usedPct ?? window.usedPercent) !== undefined ? { usedPct: window.usedPct ?? window.usedPercent } : { remainingPct: window.remainingPct }, ...(window.resetsAt ? { resetsAt: window.resetsAt } : {}), ...(window.runsOutAt ? { runsOutAt: window.runsOutAt } : {}), ...(window.scope ? { scope: window.scope } : {}) }; }); return { providerId, status: provider.status === 'available' ? 'available' : provider.status === 'error' ? 'error' : 'unavailable', ...(text(provider.planLabel, 'Paseo plan', true) !== undefined ? { planLabel: text(provider.planLabel, 'Paseo plan', true) } : {}), windows }; }) });
}
function codexbarProvider(providerId: string, raw: unknown): ProviderBudgetProvider {
  const entry = Array.isArray(raw) ? raw.find((item) => record(item, 'codexbar').provider === providerId) : undefined; const item = record(entry, 'codexbar provider'); const usage = record(item.usage, 'codexbar usage'); const pace = record(item.pace ?? {}, 'codexbar pace'); const fetchedAt = date(usage.updatedAt, 'codexbar updatedAt')!;
  const window = (value: unknown, id: string, label: string, scope: ProviderBudgetWindow['scope']): ProviderBudgetWindow | undefined => { if (!value || typeof value !== 'object') return undefined; const current = record(value, 'codexbar window'); const used = pct(current.usedPercent, 'codexbar usedPercent'); if (used === undefined) return undefined; const pacing = record(pace[id] ?? {}, 'codexbar pace'); const eta = id === 'primary' && typeof pacing.etaSeconds === 'number' && Number.isFinite(pacing.etaSeconds) ? new Date(Date.parse(fetchedAt) + pacing.etaSeconds * 1000).toISOString() : undefined; return { id, label, usedPct: used, remainingPct: used === null ? null : 100 - used, ...(date(current.resetsAt, 'codexbar resetsAt', true) !== undefined ? { resetsAt: date(current.resetsAt, 'codexbar resetsAt', true) } : {}), ...(eta ? { runsOutAt: eta } : {}), ...(typeof pacing.deltaPercent === 'number' && Number.isFinite(pacing.deltaPercent) ? { shortfallPct: Math.min(100, Math.abs(pacing.deltaPercent)) } : {}), scope }; };
  const windows = [window(usage.primary, 'primary', 'primary', 'session'), window(usage.secondary, 'secondary', 'weekly', 'weekly')].filter((value): value is ProviderBudgetWindow => Boolean(value));
  for (const extra of Array.isArray(usage.extraRateWindows) ? usage.extraRateWindows : []) { const item = record(extra, 'codexbar extra window'); const id = text(item.id, 'codexbar extra id'); const title = text(item.title, 'codexbar extra title'); const mapped = id && title ? window(item.window, id, title, 'other') : undefined; if (mapped) windows.push(mapped); }
  const cost = usage.providerCost && typeof usage.providerCost === 'object' ? record(usage.providerCost, 'codexbar balance') : undefined; const balances = cost && typeof cost.limit === 'number' ? [{ id: 'provider-cost', label: 'provider cost', used: number(cost.used, 'codexbar balance used'), remaining: number(cost.balance, 'codexbar balance remaining'), limit: number(cost.limit, 'codexbar balance limit'), unit: 'usd' as const }] : undefined;
  return { providerId, status: 'available', sourceLabel: 'codexbar', fetchedAt, windows, ...(balances ? { balances } : {}) };
}
async function run(command: string, args: string[], timeoutMs: number, maxBytes: number, envAllowlist: string[]): Promise<{ code: number | null; stdout: string }> { return new Promise((resolve, reject) => { const env: Record<string, string> = {}; for (const key of envAllowlist) if (/^[A-Z_][A-Z0-9_]*$/.test(key) && process.env[key] !== undefined) env[key] = process.env[key]!; const child = spawn(command, args, { env, stdio: ['ignore','pipe','pipe'], shell: false }); let stdout = ''; let seen = 0; let settled = false; const terminate = (message: string) => { child.kill('SIGTERM'); setTimeout(() => child.kill('SIGKILL'), 250).unref(); settle(() => reject(new Error(message))); }; const settle = (result: () => void) => { if (settled) return; settled = true; result(); }; const timeout = setTimeout(() => terminate('collector timed out'), timeoutMs); const capture = (chunk: Buffer, save: boolean) => { seen += chunk.length; if (seen > maxBytes) terminate('collector output exceeded limit'); else if (save) stdout += chunk.toString('utf8'); }; child.stdout.on('data', (chunk) => capture(chunk, true)); child.stderr.on('data', (chunk) => capture(chunk, false)); child.on('error', () => { clearTimeout(timeout); settle(() => reject(new Error('collector failed to start'))); }); child.on('close', (code) => { clearTimeout(timeout); settle(() => resolve({ code, stdout })); }); }); }
