export type WakeCategory = 'owner' | 'worker_result' | 'review' | 'steward' | 'channel_retry' | 'unknown';
export type RuntimeBudgetSample = { runtimeSessionId: string; providerId: string; model: string; mode?: string; thinking?: string; sampledAt: string; turnCountDelta?: number; inputTokensDelta?: number; cacheCreationTokensDelta?: number; cacheReadTokensDelta?: number; outputTokensDelta?: number; contextUsed?: number; contextMax?: number; wakeCategory?: WakeCategory; sourceEventId?: string };
export type RuntimeBudgetPolicy = { maxOutputTokensPerMinute: number; maxTurnsPerMinute: number; maxRepeatedWakeCount: number; contextRatio: number };
export type RuntimeBudgetSignal = 'RATE_DRAIN' | 'TURN_STORM' | 'STALE_WAKE' | 'CONTEXT_DRAIN';
export type RuntimeBudgetView = { runtimeSessionId: string; samples: number; turnCount: number; cacheReadTokens: number; cacheCreationTokens: number; outputTokens: number; velocities: { fiveMinute: number; tenMinute: number; sixtyMinute: number }; cacheReadRatio?: number; turnsPerMinute: number; contextReadPerTurn?: number; staleWakeCount: number; signals: RuntimeBudgetSignal[] };

const finite = (value: unknown) => typeof value === 'number' && Number.isFinite(value) && value >= 0 && value <= 1_000_000_000;
export function validateRuntimeBudgetSample(value: unknown): RuntimeBudgetSample {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('runtime budget sample must be an object'); const sample = value as Record<string, unknown>;
  for (const key of Object.keys(sample)) if (!['runtimeSessionId','providerId','model','mode','thinking','sampledAt','turnCountDelta','inputTokensDelta','cacheCreationTokensDelta','cacheReadTokensDelta','outputTokensDelta','contextUsed','contextMax','wakeCategory','sourceEventId'].includes(key)) throw new Error(`runtime budget sample ${key} is not allowed`);
  for (const key of ['runtimeSessionId','providerId','model','sampledAt']) if (typeof sample[key] !== 'string' || !String(sample[key]).trim() || String(sample[key]).length > 160) throw new Error(`runtime budget sample ${key} is invalid`);
  for (const key of ['mode','thinking']) if (sample[key] !== undefined && (typeof sample[key] !== 'string' || !String(sample[key]).trim() || String(sample[key]).length > 160)) throw new Error(`runtime budget sample ${key} is invalid`);
  if (!Number.isFinite(Date.parse(String(sample.sampledAt)))) throw new Error('runtime budget sample sampledAt is invalid');
  for (const key of ['turnCountDelta','inputTokensDelta','cacheCreationTokensDelta','cacheReadTokensDelta','outputTokensDelta','contextUsed','contextMax']) if (sample[key] !== undefined && !finite(sample[key])) throw new Error(`runtime budget sample ${key} is invalid`);
  if (sample.wakeCategory !== undefined && !['owner','worker_result','review','steward','channel_retry','unknown'].includes(String(sample.wakeCategory))) throw new Error('runtime budget sample wakeCategory is invalid');
  if (typeof sample.sourceEventId !== 'string' || !sample.sourceEventId.trim() || sample.sourceEventId.length > 160) throw new Error('runtime budget sample sourceEventId is required');
  return sample as RuntimeBudgetSample;
}
export class RuntimeBudgetTracker {
  private readonly samples = new Map<string, RuntimeBudgetSample[]>(); private readonly ids = new Map<string, string[]>();
  record(value: unknown): boolean { const sample = validateRuntimeBudgetSample(value); const sourceEventId = sample.sourceEventId!; const seen = this.ids.get(sample.runtimeSessionId) ?? []; if (seen.includes(sourceEventId)) return false; this.ids.set(sample.runtimeSessionId, [...seen, sourceEventId].slice(-1024)); const rows = this.samples.get(sample.runtimeSessionId) ?? []; rows.push(sample); rows.sort((a, b) => a.sampledAt.localeCompare(b.sampledAt)); this.samples.set(sample.runtimeSessionId, rows.slice(-240)); return true; }
  view(runtimeSessionId: string, policy: RuntimeBudgetPolicy, at = Date.now()): RuntimeBudgetView { const rows = (this.samples.get(runtimeSessionId) ?? []).filter((item) => Date.parse(item.sampledAt) <= at); const sum = (items: RuntimeBudgetSample[], key: keyof RuntimeBudgetSample) => items.reduce((total, item) => total + (typeof item[key] === 'number' ? item[key] as number : 0), 0); const recent = (ms: number) => rows.filter((item) => Date.parse(item.sampledAt) >= at - ms); const turns = sum(rows, 'turnCountDelta'); const read = sum(rows, 'cacheReadTokensDelta'); const creation = sum(rows, 'cacheCreationTokensDelta'); const output = sum(rows, 'outputTokensDelta'); const windowRows = recent(600_000); const elapsed = windowRows.length > 1 ? Math.max(1 / 60, (Date.parse(windowRows.at(-1)!.sampledAt) - Date.parse(windowRows[0].sampledAt)) / 60_000) : 1; const rate = (ms: number) => sum(recent(ms), 'outputTokensDelta') / Math.max(1 / 60, ms / 60_000); const stale = windowRows.filter((item) => item.wakeCategory === 'channel_retry').length; const last = rows.at(-1); const contextRatio = last?.contextUsed !== undefined && last.contextMax ? last.contextUsed / last.contextMax : undefined; const signals: RuntimeBudgetSignal[] = []; if (rate(300_000) > policy.maxOutputTokensPerMinute) signals.push('RATE_DRAIN'); if (sum(windowRows, 'turnCountDelta') / elapsed > policy.maxTurnsPerMinute) signals.push('TURN_STORM'); if (stale >= policy.maxRepeatedWakeCount) signals.push('STALE_WAKE'); if (contextRatio !== undefined && contextRatio >= policy.contextRatio) signals.push('CONTEXT_DRAIN'); return { runtimeSessionId, samples: rows.length, turnCount: turns, cacheReadTokens: read, cacheCreationTokens: creation, outputTokens: output, velocities: { fiveMinute: rate(300_000), tenMinute: rate(600_000), sixtyMinute: rate(3_600_000) }, ...(read + creation ? { cacheReadRatio: read / (read + creation) } : {}), turnsPerMinute: sum(windowRows, 'turnCountDelta') / elapsed, ...(turns ? { contextReadPerTurn: read / turns } : {}), staleWakeCount: stale, signals }; }
}
