import type { SequenceAnomaly, SequenceAnomalyProjection, SequenceEntry, SequenceProjection, SequenceRef } from './sequence-model.js';
import { compareSequenceEntries } from './sequence-model.js';

export interface SequencePatrolView { projection: SequenceAnomalyProjection; alerts: readonly SequenceAnomaly[]; highestSeverity?: SequenceAnomaly['severity']; }
const fact = (e: SequenceEntry, key: string) => e.facts[key] === undefined ? undefined : String(e.facts[key]);
const yes = (e: SequenceEntry, key: string) => e.facts[key] === true || e.facts[key] === 'true';
const refs = (e: SequenceEntry, kind: SequenceRef['kind']) => [e.subject, ...e.refs].filter((r) => r.kind === kind).map((r) => r.id);
const runtime = (e: SequenceEntry) => fact(e, 'runtimeId') ?? refs(e, 'runtime')[0] ?? (e.subject.kind === 'runtime' ? e.subject.id : undefined);
const task = (e: SequenceEntry) => fact(e, 'taskId') ?? refs(e, 'task')[0] ?? (e.subject.kind === 'task' ? e.subject.id : undefined);
const subject = (e: SequenceEntry, kind: SequenceRef['kind'], id: string): SequenceRef => ({ kind, id, ...(e.subject.kind === kind && e.subject.id === id && e.subject.label ? { label: e.subject.label } : {}) });
const groups = (items: readonly SequenceEntry[], key: (e: SequenceEntry) => string | undefined) => { const out = new Map<string, SequenceEntry[]>(); for (const e of items) { const k = key(e); if (k) out.set(k, [...(out.get(k) ?? []), e]); } return out; };
const make = (kind: SequenceAnomaly['kind'], severity: SequenceAnomaly['severity'], subjectRef: SequenceRef, proof: SequenceEntry[], headline: string, evidence: string, nextAction: string): SequenceAnomaly => { const entryIds = [...new Set(proof.map((e) => e.id))].sort(); return { id: `sequence-anomaly:${kind}:${subjectRef.kind}:${subjectRef.id}:${entryIds.join(',')}`, kind, severity, subject: subjectRef, at: proof.map((e) => e.at).sort()[0]!, entryIds, headline, evidence, owner: 'Manager', nextAction }; };

/** Pure detector over the frozen Sequence vocabulary and its graph links only. */
export function projectSequenceAnomalies(projection: SequenceProjection): SequenceAnomalyProjection {
  const entries = [...projection.entries].sort(compareSequenceEntries), anomalies: SequenceAnomaly[] = [];
  const add = (a: SequenceAnomaly) => anomalies.push(a);
  const starts = entries.filter((e) => e.kind === 'goal_started');
  const contracts = groups(entries.filter((e) => e.kind === 'goal_contract_bound'), (e) => fact(e, 'goalId'));
  const launches = entries.filter((e) => e.kind === 'runtime_launched');
  const terminalAt = (id: string) => entries.filter((e) => e.kind === 'runtime_terminal' && runtime(e) === id).map((e) => e.atMs).sort((a, b) => a - b)[0];
  const generationAt = (id: string, at: number) => entries.filter((e) => (e.kind === 'runtime_launched' || e.kind === 'runtime_generation_changed') && runtime(e) === id && e.atMs <= at).map((e) => Number(fact(e, 'generation'))).filter(Number.isFinite).sort((a, b) => b - a)[0];
  const goalForTask = (id: string) => { const launch = launches.find((e) => refs(e, 'task').includes(id)); return launch && refs(launch, 'goal')[0]; };
  const launchAtFor = (goalId: string) => launches.filter((e) => refs(e, 'goal').includes(goalId)).map((e) => e.atMs).sort((a, b) => a - b)[0];

  // The comparison is against the Goal's own runtime launch, never against
  // `goal_started`: a Goal always starts before any runtime for it launches,
  // so comparing a genuinely atomic Contract (boundAtLaunch true, timestamped
  // with its launch) against goal_started would flag every golden path.
  for (const start of starts) { const goal = fact(start, 'goalId'); if (!goal) continue; const launchAt = launchAtFor(goal); for (const contract of contracts.get(goal) ?? []) if (!yes(contract, 'boundAtLaunch') || (launchAt !== undefined && contract.atMs > launchAt)) add(make('contract_after_start', 'p0', subject(start, 'goal', goal), [start, contract], 'Goal Contract was bound after launch', 'The launch precedes a non-atomic Contract binding.', 'Stop further dispatch and relaunch with the Contract bound atomically.')); }
  for (const result of entries.filter((e) => e.kind === 'result_submitted' && fact(e, 'status') === 'candidate')) { const taskId = task(result), goal = taskId && goalForTask(taskId); const contract = goal && (contracts.get(goal) ?? []).find((e) => !yes(e, 'boundAtLaunch') || e.atMs > result.atMs); if (taskId && contract) add(make('candidate_before_contract', 'p0', subject(result, 'task', taskId), [result, contract], 'Candidate arrived before its Goal Contract', 'The candidate reaches a Goal through Task and Runtime links, and its Contract was late or non-atomic.', 'Reject the candidate and relaunch under an atomic Contract.')); }
  for (const safe of entries.filter((e) => e.kind === 'delivery_safe_point')) { const id = runtime(safe), target = Number(fact(safe, 'targetGeneration')); if (!id || !Number.isFinite(target)) continue; const terminal = terminalAt(id), current = generationAt(id, safe.atMs); if (terminal !== undefined && terminal < safe.atMs || current !== undefined && target < current) { const proof = [safe, ...entries.filter((e) => e.kind === 'runtime_terminal' && runtime(e) === id && e.atMs === terminal), ...entries.filter((e) => (e.kind === 'runtime_launched' || e.kind === 'runtime_generation_changed') && runtime(e) === id && Number(fact(e, 'generation')) === current && e.atMs <= safe.atMs).slice(-1)]; add(make('stale_safe_point', 'p1', safe.subject, proof, 'Safe point belongs to a stale runtime generation', 'The target runtime had terminated or advanced beyond the delivery target generation.', 'Route the obligation to the current generation.')); } }
  const ancestors = (e: SequenceEntry) => { const index = new Map(entries.map((x) => [x.id, x])); const seen = new Set<string>(), out: SequenceEntry[] = []; const visit = (id: string) => { if (seen.has(id)) return; seen.add(id); const parent = index.get(id); if (!parent) return; out.push(parent); parent.causal.forEach((link) => visit(link.entryId)); }; e.causal.forEach((link) => visit(link.entryId)); return out; };
  for (const delivery of entries.filter((e) => e.kind === 'delivery_delivered' || e.kind === 'delivery_processed')) { const id = runtime(delivery), target = Number(fact(delivery, 'targetGeneration')), current = id && Number.isFinite(target) ? generationAt(id, delivery.atMs) : undefined; const taskId = task(delivery), createdFence = ancestors(delivery).find((e) => e.kind === 'task_fence_advanced') && Number(fact(ancestors(delivery).find((e) => e.kind === 'task_fence_advanced')!, 'fence')); const currentFence = taskId ? entries.filter((e) => e.kind === 'task_fence_advanced' && task(e) === taskId && e.atMs <= delivery.atMs).map((e) => Number(fact(e, 'fence'))).filter(Number.isFinite).sort((a, b) => b - a)[0] : undefined; if (current !== undefined && target < current || createdFence !== undefined && currentFence !== undefined && currentFence > createdFence) add(make('late_self_wake', 'p1', delivery.subject, [delivery], 'Delivery woke a superseded runtime generation', 'The delivered or processed obligation targets a generation or Task fence that was already superseded.', 'Re-route the current obligation to the current generation and fence.')); }
  for (const [key, items] of groups(starts, (e) => fact(e, 'title') ? `title:${fact(e, 'title')}` : fact(e, 'goalId'))) if (items.length > 1) add(make('duplicate_goal', 'p1', subject(items[0]!, 'goal', fact(items[0]!, 'goalId') ?? key), items, 'Duplicate Goal launch detected', 'More than one durable goal-start entry names the same Goal title.', 'Choose one canonical Goal and retire or merge the duplicate.'));
  for (const [, items] of groups(launches, (e) => { const member = e.actor?.memberId, goal = refs(e, 'goal')[0]; return member && goal ? `${member}:${goal}` : undefined; })) { const overlap = items.filter((e, i) => i > 0 && items.slice(0, i).some((prior) => { const priorRuntime = runtime(prior), ended = priorRuntime ? terminalAt(priorRuntime) : undefined; return ended === undefined || ended > e.atMs; })); if (overlap.length) add(make('duplicate_worker', 'p1', items[0]!.subject, [items[0]!, ...overlap], 'Duplicate worker launch detected', 'The same member was launched again before the earlier runtime became terminal.', 'Keep one worker generation and reconcile the duplicate.')); }
  const claimState = new Map<string, SequenceEntry>(); for (const e of entries.filter((x) => x.kind === 'surface_claimed' || x.kind === 'surface_released')) { const id = fact(e, 'claimId'); if (id) claimState.set(id, e); } for (const [surfaceId, items] of groups([...claimState.values()].filter((e) => e.kind === 'surface_claimed' && yes(e, 'active')), (e) => fact(e, 'surfaceId'))) if (new Set(items.map((e) => fact(e, 'runtimeSessionId'))).size > 1) add(make('surface_conflict', 'p0', subject(items[0]!, 'surface', surfaceId), items, 'Concurrent writers claimed one execution surface', 'Multiple active claims name different runtime sessions for one surface.', 'Release all but one writer claim.'));
  const claims = groups(entries.filter((e) => e.kind === 'task_claimed'), (e) => `${fact(e, 'taskId') ?? ''}:${fact(e, 'fence') ?? ''}`); for (const result of entries.filter((e) => e.kind === 'result_submitted')) { const taskId = fact(result, 'taskId'), claim = claims.get(`${taskId ?? ''}:${fact(result, 'fence') ?? ''}`)?.filter((e) => e.atMs <= result.atMs).at(-1); if (taskId && claim && fact(claim, 'memberId') !== fact(result, 'memberId')) add(make('wrong_member_attribution', 'p0', subject(result, 'task', taskId), [claim, result], 'Result is attributed to a member who did not claim the Task', 'The Task-fence claimant and Result submitter differ.', 'Verify delegation evidence or require the accountable member to resubmit.')); }
  return { schemaVersion: 'arcp.sequence-anomaly/v1', generatedAt: projection.generatedAt, anomalies: anomalies.sort((a, b) => a.at.localeCompare(b.at) || a.id.localeCompare(b.id)) };
}

/** Patrol is a view over the canonical output, not a second detector. */
export function projectSequencePatrol(projection: SequenceAnomalyProjection): SequencePatrolView { const rank = { p0: 0, p1: 1, p2: 2 } as const; return { projection, alerts: projection.anomalies, ...(projection.anomalies.length ? { highestSeverity: [...projection.anomalies].sort((a, b) => rank[a.severity] - rank[b.severity])[0]!.severity } : {}) }; }
